name: Release

on:
  push:
    tags:
      - "production-*"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install codecov uv
        uv sync

    - name: Run unit test
      run: |
        uv run coverage run --omit="test/*" -m pytest

    - name: Create coverage
      run: |
        uv run coverage report
        uv run coverage xml

    - name: Push coverage to codecov
      run: |
        codecov -t "${{ secrets.CODECOV_TOKEN }}" --commit="${GITHUB_SHA}" --branch="master"


  build_and_publish:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync

    - name: Build package
      run: |
        uv build

    - name: Publish package
      run: |
        uv publish -t "${{ secrets.PYPI_TOKEN }}"


#  github_release:
#    name: Create GitHub Release
#    needs: build_and_publish
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Fetch full history to avoid issues with tags and branches
#
#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: dist
#          path: dist/